namespace Contracts
{
    /// <summary>
    /// Event published by the Workout Service immediately after a user successfully
    /// executes the POST /api/v1/workouts/{id}/start endpoint.
    /// This signals the Progress Tracking Service to create an Active Session record.
    /// </summary>
    public record WorkoutSessionStartedEvent
    {
        // --- Transactional/Identity Data ---

        /// <summary>
        /// The unique ID generated by the Workout Service and returned to the client.
        /// The Progress Tracking Service MUST use this as the primary key for the active session.
        /// </summary>
        public required string SessionId { get; init; }

        /// <summary>
        /// The ID of the authenticated user who started the session.
        /// </summary>
        public required string UserId { get; init; }

        /// <summary>
        /// The ID of the workout plan being followed (e.g., WkId_FullBody).
        /// </summary>
        public required Guid WorkoutId { get; init; }

        /// <summary>
        /// The UTC timestamp when the session was initiated.
        /// </summary>
        public required DateTime StartedAtUtc { get; init; }


        /// <summary>
        /// The UTC timestamp when the session Ends.
        /// </summary>
        public required DateTime DeadlineUtc { get; init; }

        

        // --- Workout Metadata for Tracking ---

        /// <summary>
        /// The planned duration of the workout, derived from the request body or catalog.
        /// </summary>
        public required int PlannedDurationMinutes { get; init; }

        /// <summary>
        /// The chosen or assigned difficulty level (e.g., 'Intermediate').
        /// </summary>
        public required string DifficultyLevel { get; init; }
    }
}