using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared;
using UserProfileService.Entities;

namespace UserProfileService.DataBase.Configurations;

public class UserProfileConfigurations : IEntityTypeConfiguration<UserProfile>
{
    public void Configure(EntityTypeBuilder<UserProfile> builder)
    {
        builder.ToTable("UserProfiles");

        // --- Primary Key ---
        builder.HasKey(p => p.Id);


        // This is the most important part of the configuration.
        // It tells EF Core that the UserId is NOT auto-generated by the database.
        // We provide it from the AuthenticationService.
        builder.Property(p => p.Id)
            .ValueGeneratedNever();


        // --- Column Properties ---
        builder.Property(p => p.UserName)
            .IsRequired(false)
            .HasMaxLength(100);

        

        builder.Property(p => p.Email)
            .IsRequired(false);

        builder.HasIndex(p => p.Email)
            .IsUnique();

        // Configure MemberSince to have a default value in SQL
        builder.Property(p => p.MemberSince)
            .HasDefaultValueSql("GETUTCDATE()"); // SQL Server equivalent of DateTime.UtcNow

        
        builder.Property(p => p.ProfilePictureUrl)
            .IsRequired(false);

        builder.Property(p => p.DateOfBirth)
            .HasColumnType("date"); // Store as 'date' in SQL, not 'datetime'

        builder.Property(p => p.Weight)
            .IsRequired(false);

        builder.Property(p => p.Height)
            .IsRequired(false);

        builder.Property(p => p.PrimaryGoal)
            .HasMaxLength(100)
            .IsRequired(false);


        builder.Property(p => p.ActivityLevel)
               .HasConversion(
                   convertToProviderExpression: (ActivityLevel) => ActivityLevel.ToString(),
                   convertFromProviderExpression: (_type) => (ActivityLevel)Enum.Parse(typeof(ActivityLevel), _type));

        builder.Property(p => p.ActivityLevel)
               .HasConversion<string>()
               .HasMaxLength(50)
               .IsRequired(false);
    }
}
